eliecer_principal_homepage:
    path:       /
    defaults:   { _controller: EliecerPrincipalBundle:Default:index }

eliecer_admin:
    path:       /admin
    defaults:   { _controller: EliecerPrincipalBundle:Admin:index }
