parameters:
#    eliecer_principal.example.class: Eliecer\PrincipalBundle\Example

services:
#    eliecer_principal.example:
#        class: %eliecer_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
